### ISSUE TITLE
Warnings with PHP 8.1

### ISSUE THREAD

**Issue by akiessling** [baschte/content-animations#11]
When opening an content element in a fresh TYPO3 11 setup with PHP 8.1 i get the following warnings (using extension version 2.3.1)

```
PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "header" in /var/www/html/src/private/typo3conf/ext/content_animations/Classes/Form/Elements/AnimationPreviewField.php line 135

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key 0 in /var/www/html/src/private/typo3conf/ext/content_animations/Classes/Form/Elements/AnimationPreviewField.php line 193
```

**Comment by baschte** [comment]
Hey @akiessling 
thx for your hint with the php 8.1 issues.

I fixed them in the actual master branch. Maybe you can test it by using the dev-master branch in your composer and give me some feedback if the problem is gone. Then i'll release a new version with php 8.1 support.

greetings

**Comment by akiessling** [comment]
Hi @baschte 
i still get an exception here

https://github.com/baschte/content-animations/blob/master/Classes/Form/Elements/AnimationPreviewField.php#L193

Should this become 
`$html[] = '<div class="ce-preview" data-aos="' . ($parameterArray['itemFormElValue']['0'] ?? '') . '">';` ?

**Comment by baschte** [comment]
hi @akiessling,
does your fix solves the error Message in your project? Cant check it out right now.

**Comment by baschte** [comment]
hey @akiessling,
please test the actual master in your project and give me some feedback please. 
The problem should be solved now. My projects are working fine now with php 8.1 :-)

greetings

**Comment by akiessling** [comment]
Looks good to me now @baschte 
Thanks for taking care!

**Comment by baschte** [comment]
@akiessling 
you're welcome!

New version 2.3.2 is out! 
https://github.com/baschte/content-animations/releases/tag/2.3.2

Have fun
